using System.Text;

namespace TenSecondTom.Features.Generate.Models;

/// <summary>
/// Result of LLM processing with comprehensive metadata.
/// Represents the complete output including content, generation details, and token usage.
/// </summary>
public sealed record GeneratedOutput
{
    /// <summary>
    /// Gets the generated content from LLM.
    /// </summary>
    public required string Content { get; init; }

    /// <summary>
    /// Gets the base name of the source recording.
    /// </summary>
    public required string RecordingBaseName { get; init; }

    /// <summary>
    /// Gets the template ID used for generation.
    /// </summary>
    public required string TemplateId { get; init; }

    /// <summary>
    /// Gets the template title for display.
    /// </summary>
    public required string TemplateTitle { get; init; }

    /// <summary>
    /// Gets the timestamp when output was generated.
    /// </summary>
    public required DateTimeOffset GeneratedAt { get; init; }

    /// <summary>
    /// Gets the LLM provider used.
    /// </summary>
    public required string ProviderName { get; init; }

    /// <summary>
    /// Gets the model used for generation.
    /// </summary>
    public required string ModelName { get; init; }

    /// <summary>
    /// Gets the number of input tokens consumed.
    /// </summary>
    public required int InputTokens { get; init; }

    /// <summary>
    /// Gets the number of output tokens generated.
    /// </summary>
    public required int OutputTokens { get; init; }

    /// <summary>
    /// Gets whether the input was truncated due to token limits.
    /// </summary>
    public required bool WasTruncated { get; init; }

    /// <summary>
    /// Gets the original transcript word count (before truncation).
    /// </summary>
    public required int OriginalWordCount { get; init; }

    /// <summary>
    /// Gets the output file path where content was saved.
    /// </summary>
    public string? OutputFilePath { get; init; }

    /// <summary>
    /// Gets the total tokens used (input + output).
    /// </summary>
    public int TotalTokens => InputTokens + OutputTokens;

    /// <summary>
    /// Formats the output as markdown with metadata header.
    /// The metadata is included as HTML comments at the beginning of the file.
    /// </summary>
    /// <returns>A markdown-formatted string with metadata and content.</returns>
    public string ToMarkdown()
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by Ten Second Tom -->");
        sb.AppendLine($"<!-- Recording: {RecordingBaseName}.txt -->");
        sb.AppendLine($"<!-- Template: {TemplateId} ({TemplateTitle}) -->");
        sb.AppendLine($"<!-- Generated: {GeneratedAt:O} -->");
        sb.AppendLine($"<!-- Provider: {ProviderName} ({ModelName}) -->");
        sb.AppendLine($"<!-- Tokens: {InputTokens} input, {OutputTokens} output -->");

        if (WasTruncated)
        {
            sb.AppendLine($"<!-- Truncated: Yes (original {OriginalWordCount} words) -->");
        }

        sb.AppendLine();
        sb.AppendLine(Content);

        return sb.ToString();
    }
}
