using System.Collections.Concurrent;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TenSecondTom.Infrastructure.Notifications.Channels;
using TenSecondTom.Infrastructure.Notifications.Security;
using TenSecondTom.Shared.Abstractions.Notifications;
using TenSecondTom.Shared.Models;
using TenSecondTom.Shared.Options;
using TenSecondTom.Shared.Results;

namespace TenSecondTom.Infrastructure.Notifications;

/// <summary>
/// Core notification service that manages routing notifications to available channels.
/// Handles channel selection, token security for interactive actions, and notification state tracking.
/// </summary>
/// <remarks>
/// <para>
/// The service uses a multi-channel architecture where notifications can be sent through
/// different providers (OS native, Slack, Teams, etc.). At runtime, the service selects
/// the first available channel that supports the notification's requirements.
/// </para>
/// <para>
/// <strong>Channel Selection Strategy:</strong>
/// </para>
/// <list type="number">
/// <item>Query all registered channels for availability (platform compatibility, configuration)</item>
/// <item>Filter channels by capability requirements (interactivity, custom timeout, etc.)</item>
/// <item>Select first available channel that meets requirements</item>
/// <item>Gracefully degrade if no suitable channel found (based on SilentFallback setting)</item>
/// </list>
/// <para>
/// <strong>Security:</strong>
/// </para>
/// <para>
/// Interactive notifications automatically have their actions secured with HMAC tokens
/// to prevent tampering with callback URLs. Tokens are generated by INotificationTokenService
/// and validated when actions are triggered.
/// </para>
/// </remarks>
public sealed class NotificationService : INotificationService
{
    private readonly IEnumerable<INotificationChannel> _channels;
    private readonly INotificationTokenService _tokenService;
    private readonly NotificationOptions _options;
    private readonly ILogger<NotificationService> _logger;

    // Track notification states in memory (simple implementation)
    // For production, consider persistent storage or external state management
    private readonly ConcurrentDictionary<Guid, NotificationState> _notificationStates = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="NotificationService"/> class.
    /// </summary>
    /// <param name="channels">All registered notification channels (OS native, Slack, etc.).</param>
    /// <param name="tokenService">Service for generating and validating action tokens.</param>
    /// <param name="options">Notification configuration options.</param>
    /// <param name="logger">Logger instance for diagnostics.</param>
    public NotificationService(
        IEnumerable<INotificationChannel> channels,
        INotificationTokenService tokenService,
        IOptions<NotificationOptions> options,
        ILogger<NotificationService> logger)
    {
        _channels = channels ?? throw new ArgumentNullException(nameof(channels));
        _tokenService = tokenService ?? throw new ArgumentNullException(nameof(tokenService));
        _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<Guid>> SendAsync(Notification notification, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(notification);

        // Check if notifications are enabled
        if (!_options.Enabled)
        {
            _logger.LogDebug("Notifications disabled in configuration. Notification {NotificationId} not sent.", notification.NotificationId);
            return _options.SilentFallback
                ? Result<Guid>.Success(notification.NotificationId)
                : Result<Guid>.Failure("Notifications are disabled in configuration");
        }

        _logger.LogInformation(
            "Sending notification: NotificationId={NotificationId}, Title={Title}, Priority={Priority}",
            notification.NotificationId,
            notification.Title,
            notification.Priority);

        // Select an available channel
        var channelResult = await SelectChannelAsync(
            requireInteractivity: false,
            cancellationToken);

        if (!channelResult.IsSuccess)
        {
            _logger.LogWarning(
                "No notification channel available for notification {NotificationId}: {Error}",
                notification.NotificationId,
                channelResult.Error);

            return _options.SilentFallback
                ? Result<Guid>.Success(notification.NotificationId)
                : Result<Guid>.Failure($"No notification channel available: {channelResult.Error}");
        }

        var channel = channelResult.Value;

        _logger.LogDebug(
            "Selected channel {ChannelName} for notification {NotificationId}",
            channel.ChannelName,
            notification.NotificationId);

        // Track notification state
        _notificationStates[notification.NotificationId] = NotificationState.Pending;

        // Send notification through selected channel
        var sendResult = await channel.SendAsync(notification, cancellationToken);

        if (sendResult.IsSuccess)
        {
            _notificationStates[notification.NotificationId] = NotificationState.Displayed;
            _logger.LogInformation(
                "Notification sent successfully: NotificationId={NotificationId}, Channel={ChannelName}",
                notification.NotificationId,
                channel.ChannelName);
        }
        else
        {
            _notificationStates[notification.NotificationId] = NotificationState.Failed;
            _logger.LogError(
                "Failed to send notification {NotificationId} via {ChannelName}: {Error}",
                notification.NotificationId,
                channel.ChannelName,
                sendResult.Error);

            return _options.SilentFallback
                ? Result<Guid>.Success(notification.NotificationId)
                : sendResult;
        }

        return sendResult;
    }

    /// <inheritdoc/>
    public async Task<Result<Guid>> SendInteractiveAsync(Notification notification, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(notification);

        if (notification.Actions.Count == 0)
        {
            _logger.LogWarning(
                "SendInteractiveAsync called for notification {NotificationId} with no actions. Use SendAsync for non-interactive notifications.",
                notification.NotificationId);
            return await SendAsync(notification, cancellationToken);
        }

        _logger.LogInformation(
            "Sending interactive notification: NotificationId={NotificationId}, Title={Title}, ActionCount={ActionCount}",
            notification.NotificationId,
            notification.Title,
            notification.Actions.Count);

        // Select a channel that supports interactivity
        var channelResult = await SelectChannelAsync(
            requireInteractivity: true,
            cancellationToken);

        if (!channelResult.IsSuccess)
        {
            _logger.LogWarning(
                "No interactive notification channel available for notification {NotificationId}: {Error}. Falling back to basic notification.",
                notification.NotificationId,
                channelResult.Error);

            // Graceful degradation: Try to send as basic notification without actions
            var basicNotification = notification with { Actions = [] };
            return await SendAsync(basicNotification, cancellationToken);
        }

        var channel = channelResult.Value;

        _logger.LogDebug(
            "Selected interactive channel {ChannelName} for notification {NotificationId}",
            channel.ChannelName,
            notification.NotificationId);

        // Attach security tokens to actions
        var securedActions = notification.Actions
            .Select(action =>
            {
                var token = _tokenService.GenerateToken(notification.NotificationId, action.ActionId);
                return action.WithToken(token);
            })
            .ToList();

        var securedNotification = notification with { Actions = securedActions };

        _logger.LogDebug(
            "Attached security tokens to {ActionCount} actions for notification {NotificationId}",
            securedActions.Count,
            notification.NotificationId);

        // Track notification state
        _notificationStates[notification.NotificationId] = NotificationState.Pending;

        // Send notification through selected channel
        var sendResult = await channel.SendAsync(securedNotification, cancellationToken);

        if (sendResult.IsSuccess)
        {
            _notificationStates[notification.NotificationId] = NotificationState.Displayed;
            _logger.LogInformation(
                "Interactive notification sent successfully: NotificationId={NotificationId}, Channel={ChannelName}",
                notification.NotificationId,
                channel.ChannelName);
        }
        else
        {
            _notificationStates[notification.NotificationId] = NotificationState.Failed;
            _logger.LogError(
                "Failed to send interactive notification {NotificationId} via {ChannelName}: {Error}",
                notification.NotificationId,
                channel.ChannelName,
                sendResult.Error);

            return _options.SilentFallback
                ? Result<Guid>.Success(notification.NotificationId)
                : sendResult;
        }

        return sendResult;
    }

    /// <inheritdoc/>
    public Task<Result<NotificationState>> GetStateAsync(Guid notificationId, CancellationToken cancellationToken)
    {
        if (_notificationStates.TryGetValue(notificationId, out var state))
        {
            _logger.LogDebug("Retrieved state for notification {NotificationId}: {State}", notificationId, state);
            return Task.FromResult(Result<NotificationState>.Success(state));
        }

        _logger.LogWarning("Notification {NotificationId} not found in state tracking", notificationId);
        return Task.FromResult(Result<NotificationState>.Failure($"Notification {notificationId} not found"));
    }

    /// <summary>
    /// Selects the first available notification channel that meets the specified requirements.
    /// </summary>
    /// <param name="requireInteractivity">Whether the channel must support interactive actions.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// A result containing the selected channel, or a failure if no suitable channel is available.
    /// </returns>
    private async Task<Result<INotificationChannel>> SelectChannelAsync(
        bool requireInteractivity,
        CancellationToken cancellationToken)
    {
        _logger.LogDebug(
            "Selecting notification channel: RequireInteractivity={RequireInteractivity}, RegisteredChannels={ChannelCount}",
            requireInteractivity,
            _channels.Count());

        foreach (var channel in _channels)
        {
            // Check if channel is available (platform compatibility, configuration, etc.)
            var availabilityResult = await channel.IsAvailableAsync(cancellationToken);

            if (!availabilityResult.IsSuccess)
            {
                _logger.LogDebug(
                    "Channel {ChannelName} not available: {Reason}",
                    channel.ChannelName,
                    availabilityResult.Error);
                continue;
            }

            // Check if channel meets capability requirements
            if (requireInteractivity && !channel.Capabilities.SupportsInteractivity)
            {
                _logger.LogDebug(
                    "Channel {ChannelName} does not support interactivity",
                    channel.ChannelName);
                continue;
            }

            _logger.LogDebug("Selected channel {ChannelName}", channel.ChannelName);
            return Result<INotificationChannel>.Success(channel);
        }

        var errorMessage = requireInteractivity
            ? "No interactive notification channel available on this platform"
            : "No notification channel available on this platform";

        _logger.LogDebug("Channel selection failed: {Error}", errorMessage);
        return Result<INotificationChannel>.Failure(errorMessage);
    }
}
